In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
lewis=pd.read_csv('Heart_Disease_Prediction.csv')

In [2]:
lewis

,index,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence
266,266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence
267,267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence
268,268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence
269,269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence

In [5]:
lewis.head()

,index,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence

In [12]:
lewis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   index                    270 non-null    int64
 1   Age                      270 non-null    int64
 2   Sex                      270 non-null    int64
 3   Chest pain type          270 non-null    int64
 4   BP                       270 non-null    int64
 5   Cholesterol              270 non-null    int64
 6   FBS over 120             270 non-null    int64
 7   EKG results              270 non-null    int64
 8   Max HR                   270 non-null    int64
 9   Exercise angina          270 non-null    int64
 10  ST depression            270 non-null    float64
 11  Slope of ST              270 non-null    int64
 12  Number of vessels fluro  270 non-null    int64
 13  Thallium                 270 non-null    int64
 14  Heart Disease            270 non-null    object
dtypes: float64(1), int64(13), object(1)
memory usage: 31.8+ KB

In [20]:
#plot graph
data=pd.DataFrame(lewis)

In [21]:
data

,index,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence
266,266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence
267,267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence
268,268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence
269,269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence

In [28]:
fig=plt.figure()

In [29]:
x=lewis['Sex']
y=lewis['ST depression']
plt.show()

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
import statsmodels.api as sm

# Load the dataset
lewis=pd.read_csv('Heart_Disease_Prediction.csv')
X = X = pd.DataFrame(heart_disease_data.drop(columns=['Heart Disease']), columns=heart_disease_data.drop(columns=['ST depression']).columns)
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create and train the logistic regression model
model = LogisticRegression(max_iter=10000, multi_class='multinomial')
model.fit(X_train, y_train)

# Make predictions and evaluate the model
predictions = model.predict(X_test)
print("\nConfusion Matrix:\n", confusion_matrix(y_test, predictions))
print("\nClassification Report:\n", classification_report(y_test, predictions))

# Analyze the coefficients
coefficients = pd.DataFrame(model.coef_, columns=X.columns)
coefficients['intercept'] = model.intercept_
print("\nCoefficients of the model:\n", coefficients)

# If you want p-values and more statistics, use statsmodels
X_train_const = sm.add_constant(X_train) # adding a constant

model_sm = sm.MNLogit(y_train, X_train_const)
result = model_sm.fit()

print(result.summary())


# In[ ]:

NameError: name 'heart_disease_data' is not defined